use FiapSmartCity

CREATE TABLE PRODUTO (
  IDPRODUTO         int identity(1,1)        PRIMARY KEY,
  NOMEPRODUTO       VARCHAR(70)   NOT NULL,
  CARACTERISTICAS   VARCHAR(100)  NOT NULL,
  PRECOMEDIO        money,
  LOGOTIPO      	VARCHAR(200) NOT NULL,
  ATIVO  	INT,
  IDTIPO    INT,
  CONSTRAINT FK_IDTIPO FOREIGN KEY (IDTIPO) 
  REFERENCES TIPOPRODUTOEF(IDTIPO)
);


SELECT * FROM PRODUTO;
SELECT * FROM TIPOPRODUTOEF;

 INSERT INTO PRODUTO (NOMEPRODUTO, CARACTERISTICAS, PRECOMEDIO, LOGOTIPO, ATIVO, IDTIPO  )
              VALUES ('Produto Tinta 1','Caracteristicas', 2000, 'http://www.logo.com.br/tinta1', 1, 1);
